version: '3'
services:
  nginex-app:
    image: nginx:alpine
    ports:
      - "80:8000"
    environment:
      - PORT=80
    env_file:
      - ./.env
    # volumes:
    #   - /home/ubuntu/horticorp-vipani/naadanvipani-frontend:/etc/nginx/nginx.conf